name: Delete Branch

on:
  issue_comment:
    types:
      - created  # Runs when a comment is added to a PR

jobs:
  delete-branch:
    name: Delete Branch on User Confirmation
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == '/delete-branch'

    steps:
      - name: Delete Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          BRANCH_NAME=$(gh pr view $PR_NUMBER --json headRefName -q .headRefName)
          REPO=${{ github.repository }}

          echo "Deleting branch: $BRANCH_NAME"
          curl -X DELETE -H "Authorisation: Bearer $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH_NAME